### collection
GET https://boardgamegeek.com/xmlapi2/collection?username=lesconjures&brief=1

>>! bgg-collection.xml

### boardgame
GET https://boardgamegeek.com/xmlapi2/things?id=68448,348554,287954&type=boardgame&versions=1&stats=1

>>! bgg-boardgames.xml